# Streamlit Cloud Secrets Template
# Copy this exact format to your Streamlit Cloud secrets

[connections.sql]
url = "postgresql://postgres:Sit%401125@db.vbowznmcdzsgzntnzwfi.supabase.co:5432/postgres"

# Alternative format (if the above doesn't work):
# [connections]
# sql = "postgresql://postgres:Sit%401125@db.vbowznmcdzsgzntnzwfi.supabase.co:5432/postgres"
