# Streamlit Secrets Template for Reflexta Analytics Platform
# Copy this file to .streamlit/secrets.toml and fill in your actual values

# Database Connection
[connections.sql]
url = "postgresql+psycopg://postgres:Sit%401125@localhost:5432/Test"

# DeepSeek API Configuration for AI Assistant
deepseek_api_key = "sk-0f8f14e071d34831aabf892ea372de2f"

# Optional: Additional API configurations
# [api_keys]
# openai_api_key = "your_openai_key_here"
# anthropic_api_key = "your_anthropic_key_here"

# Application Settings
[app_settings]
debug_mode = false
cache_ttl = 60
max_chat_history = 10

# AI Assistant Settings
[ai_assistant]
model = "deepseek-chat"
max_tokens = 500
temperature = 0.7
timeout_seconds = 30
