# WARNING: This file is an example template. Do NOT commit real secrets.
# Provide your database URL below. Streamlit will read it at runtime.

[connections.sql]
# PostgreSQL (default)
# Format: postgresql+psycopg://USER:PASS@HOST:PORT/DBNAME
# Example pattern: postgresql+psycopg://postgres:Sit%401125@localhost:5432/Test
url = "postgresql+psycopg://postgres:Sit%401125@localhost:5432/Test"

# Oracle (optional; leave commented until needed)
# Format: oracle+oracledb://USER:PASS@HOST:PORT/SERVICE_NAME
# url = "oracle+oracledb://USER:PASS@HOST:PORT/SERVICE_NAME"


